version: '3'

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:rw
      - ./mosquitto/log/:/mosquitto/log/
      - data:/mosquitto/data/
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=measurements
    ports:
      - "5432:5432"

volumes:
  data:
  postgres_data:
