version: '3'

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:rw
      - ./mosquitto/log/:/mosquitto/log/
      - data:/mosquitto/data/
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: postgres:15
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=measurements
      - TZ=Europe/Athens
    ports:
      - "5432:5432"

  script:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mqtt
      - db

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db
      GF_DATABASE_NAME: measurements
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: postgres
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  data:
  postgres_data:
  grafana_data:
